server:
  port: 8084

spring:
  application:
    name: search-service
  cloud:
    nacos:
      discovery:
        server-addr: ${SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR:nacos:8848}
        username: ${SPRING_CLOUD_NACOS_DISCOVERY_USERNAME:nacos}
        password: ${SPRING_CLOUD_NACOS_DISCOVERY_PASSWORD:nacos}
    sentinel:
      transport:
        dashboard: sentinel:8858

feign:
  sentinel:
    enabled: true

